POST http://localhost:8080/api/emails
Content-Type: application/json

{
  "toAddress": ["mohdzaid12574@gmail.com"],
  "subject": "Test Email",
  "body": "Hello from backend",
  "attachmentName": "../../Insurance.pdf"
  }